#pragma once
#include <allegro5/allegro.h>
#include <allegro5/allegro5.h>
#include <allegro5/allegro_image.h>
#include "allegro5/allegro_font.h"
#include "allegro5/allegro_audio.h"
#include "allegro5/allegro_primitives.h"
#include "allegro5/allegro_ttf.h"
#include "allegro5/allegro_acodec.h"
#include "allegro5/utf8.h"
#include "allegro5/allegro_physfs.h"
#include "allegro5/allegro_windows.h"
#include "allegro5/allegro_direct3d.h"